const ADMIN_LOCALES = {
  'zh-CN': {
    common: {
      cancel: '取消',
      save: '保存',
      delete: '删除',
      close: '关闭',
      all: '全部',
    },
    sidebar: {
      brand: 'VistaFlow',
      subtitle: '管理控制台',
      dataOps: '数据运营',
      system: '系统',
      overview: '概览仪表盘',
      tasks: '任务调度中心',
      data: '数据管理',
      config: '系统配置',
      log: '操作日志',
      adminName: 'Admin',
      adminRole: '超级管理员',
    },
    page: {
      headerEyebrow: '管理控制台',
      refresh: '刷新',
      lastRefresh: (timestamp: string) => `最近刷新：${timestamp}`,
    },
    routeMeta: {
      overview: { title: '数据概览', subtitle: '实时监控 · 每 30 秒自动刷新' },
      tasks: { title: '任务调度中心', subtitle: '管理后台抓取、补全、清洗与人工确认任务' },
      data: { title: '数据管理', subtitle: '浏览、编辑与导出站点及结构化基础数据' },
      config: { title: '系统参数配置', subtitle: '维护外部凭证、代理设置与全局运行开关' },
      log: { title: '操作日志', subtitle: '查看任务事件、系统告警与人工操作记录' },
    },
    overview: {
      totalRecords: '总记录数',
      totalRecordsTrend: '今日 +2,847',
      stationCoverage: '站点覆盖数',
      coordCompletion: '坐标补全率',
      pendingAlerts: '待处理告警',
      pendingAlertsSubtitle: '1 项需人工确认',
      todayApiCalls: '今日 API 调用',
      remainingQuota: '余量',
      dataPulse: '数据脉冲',
      dataIngestionTrend: '数据录入趋势',
      trendSubtitle: '近 7 天录入与更新情况',
      apiUsage: 'API 使用率',
      amapService: '高德地图服务',
      quotaUsed: '已使用',
      quotaReset: '重置于',
      activeTasks: '活跃任务',
      systemAlerts: '系统告警',
      viewAll: '查看全部 →',
      viewLogs: '查看日志 →',
      range7d: '7天',
      range30d: '30天',
      operationsEyebrow: '运营',
      signalEyebrow: '信号',
      taskSyncName: '车次状态同步 T+15',
      taskReviewName: '站点坐标补全复核',
      taskFullFetchName: '基础车站全量抓取',
      pendingBadge: '待确认',
      completedBadge: '已完成',
      credentialExpired: '代理凭证已过期',
      credentialExpiredDesc: '票务代理 Token 已失效，会影响实时票价查询。',
      apiQuotaWarning: 'API 配额预警',
      apiQuotaWarningDesc: '高德地图 API 已使用 75%，预计 2 天后耗尽。',
      fullSyncDone: '全量抓取完成',
      fullSyncDoneDesc: '已入库 3,412 条车站记录，耗时 2 分 14 秒。',
    },
    tasks: {
      activeTotal: '活跃 / 总数',
      running: '运行中',
      pendingConfirm: '待人工确认',
      errorTerminated: '异常终止',
      searchPlaceholder: '搜索任务名称…',
      newTask: '新建任务',
      allStatus: '全部状态',
      statusRunning: '运行中',
      statusPending: '待确认',
      statusDone: '已完成',
      statusError: '异常',
      statusTerminated: '已终止',
      stop: '终止',
      details: '详情',
      previewConfirm: '预览并确认',
      restart: '重新执行',
      goFix: '前往修复',
      taskDetailsInDev: '任务详情功能开发中',
    },
    taskDrawer: {
      eyebrow: '新建任务',
      title: '配置调度任务',
      subtitle: '统一配置抓取、补全、更新与清理任务的执行参数。',
      name: '任务名称',
      namePlaceholder: '例如：核心线路票源同步',
      type: '任务类型',
      dateOffset: '目标日期偏移',
      dateOffsetPlaceholder: '例如：T+0 至 T+30',
      cronEnabled: '定时自动执行',
      cronExpr: 'Cron 表达式',
      cronHint: '每 15 分钟执行一次。下次执行于 ',
      retry: '失败重试',
      retryTimes: '次，间隔',
      retrySeconds: '秒',
      submit: '部署任务',
      defaultTaskName: '新任务',
      types: {
        fetchStatus: '车次实时状态同步',
        fetchStation: '基础车站静态抓取',
        geocode: '站点经纬度补全',
        price: '票价矩阵更新',
        cleanup: '过期数据清理',
      },
    },
    data: {
      stationData: '车站数据',
      routeData: '线路数据',
      priceMatrix: '票价矩阵',
      searchPlaceholder: '搜索站点名称或编码…',
      exportCsv: '导出 CSV',
      addStation: '新增站点',
      allStatus: '全部状态',
      coordComplete: '坐标完整',
      lowConfidence: '低置信度',
      coordMissing: '坐标缺失',
      verify: '核实',
      edit: '编辑',
      statusComplete: '完整',
      statusMissing: '缺失',
      recordsCount: (count: number) => `共 ${count} 条记录`,
      prevPage: '上一页',
      nextPage: '下一页',
      exportInDev: '导出功能开发中',
      addInDev: '新增站点功能开发中',
      paginationInDev: '分页功能开发中',
      routeModuleTitle: '线路数据模块',
      routeModuleDesc: '后续将接入线路关系与开行图谱。',
      priceModuleTitle: '票价矩阵模块',
      priceModuleDesc: '需要先完成凭证与代理配置后启用。',
      goConfig: '前往配置',
    },
    stationDrawer: {
      eyebrow: '站点编辑',
      title: '编辑站点',
      subtitle: (name?: string) => (name ? `当前站点：${name}` : '维护站点基础信息、来源与经纬度置信度。'),
      name: '站点名称',
      code: '站点编码',
      city: '所属城市',
      longitude: '经度 (Lng)',
      latitude: '纬度 (Lat)',
      confidence: '经纬度置信度',
      confidenceSource: '来源：高德地图 API · 2026-03-28 自动解析',
      dataSource: '数据来源标记',
      notes: '备注',
      notesPlaceholder: '添加备注…',
      dataSources: {
        amap: '高德地图 API',
        manual: '人工录入',
        scraped: '爬虫抓取',
      },
    },
    config: {
      description: '管理后台依赖的外部凭证与运行开关。修改后会立即生效，建议每次更新后执行一次连通性检测。',
      credentialEyebrow: '凭证',
      healthyStatus: '正常可用',
      expiredStatus: '已过期',
      editConfig: '编辑配置',
      testConnection: '连通性检测',
      testing: '检测中...',
      updateCredential: '更新凭证',
      clearOverride: '清除覆盖值',
      runtimeEyebrow: '运行时',
      globalToggles: '全局开关',
      togglesSubtitle: '影响后台与自动化任务行为的共享开关。',
      credentialEditorInDev: '打开凭证编辑器',
      updatePanelInDev: '打开凭证更新面板',
      overrideCleared: '已清除覆盖值',
      connectionOk: '连通性测试通过 · 延迟 42ms',
    },
    log: {
      searchPlaceholder: '搜索关键字…',
      allSeverity: '全部级别',
      exportLogs: '导出日志',
    },
    preview: {
      eyebrow: '人工确认',
      title: '经纬度补全 · 数据预览与确认',
      subtitle: '统一过滤预解析结果，确认后再写入站点主数据。',
      searchPlaceholder: '搜索站点名称…',
      successOnly: '仅成功项',
      failedOnly: '仅失败项',
      all: '全部',
      failedBadge: '失败',
      selectedSummary: (selected: number, failed: number) => `已选 ${selected} 项 · ${failed} 项失败已跳过`,
      confirm: '确认并落库',
    },
    toast: {
      dataRefreshed: '数据已刷新',
      taskTerminated: '任务已强制终止',
      taskRestarted: '任务已重新加入执行队列',
      taskCreated: (name: string) => `任务“${name}”已成功下发`,
      stationSaved: '站点信息已保存',
      stationDeleted: '站点数据已删除',
      previewConfirmed: '3 条数据已确认写入',
      updateCredentialFirst: '请先更新代理凭证',
      featureInDev: (name: string) => `${name}功能开发中`,
      logsExported: '日志已导出',
    },
  },
} as const;

const ADMIN_LABEL_LOCALE = 'zh-CN' as const;
const ADMIN_LABELS = ADMIN_LOCALES[ADMIN_LABEL_LOCALE];

export const COMMON_LABELS = ADMIN_LABELS.common;
export const SIDEBAR_LABELS = ADMIN_LABELS.sidebar;
export const PAGE_LABELS = ADMIN_LABELS.page;
export const ROUTE_META_LABELS = ADMIN_LABELS.routeMeta;
export const OVERVIEW_LABELS = ADMIN_LABELS.overview;
export const TASK_LABELS = ADMIN_LABELS.tasks;
export const TASK_DRAWER_LABELS = ADMIN_LABELS.taskDrawer;
export const DATA_LABELS = ADMIN_LABELS.data;
export const STATION_DRAWER_LABELS = ADMIN_LABELS.stationDrawer;
export const CONFIG_LABELS = ADMIN_LABELS.config;
export const LOG_LABELS = ADMIN_LABELS.log;
export const PREVIEW_LABELS = ADMIN_LABELS.preview;
export const TOAST_MESSAGES = ADMIN_LABELS.toast;
